# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: doronfe/details-app-helm
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8000
  targetPort: 8000

ingress:
  enabled: true
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
